INIT_POSITIONS_X:
  first: 0.0 

INIT_POSITIONS_Y:
  first: 3

INIT_POSITIONS_THETA:
  first: 45
  
GOAL_POSITIONS_X:
  first: 4.0 

GOAL_POSITIONS_Y:
  first: 4.0

GOAL_POSITIONS_THETA:
  first: 45

A_COEF:
  LASER: 2

K_COEF:
  LASER: 0.5
  TARGET: 0.9

SAFE_DISTANCE: 3
DANGER_DISTANCE: 0.2
SAMPLE_DISTANCE: 0.05
MAX_LIDAR_DISTANCE: 3.1
NUM_POINTS: 20
V_K: 0.03
REACH_GOAL: 0.1
USE_TRADITION: False
USE_SAMPLE: True
ONLY_PLAN: False
DYNAMIC: False
